### ISSUE TITLE
ch3下划线的一点翻译问题

### ISSUE THREAD

**Issue by WJ-Yuan** [ten-ltw/JavaScript-The-Definitive-Guide-7th-zh#3]
`At the time of this writing in early 2020, underscores in numeric literals are not yet formally standardized as part of JavaScript. But they are in the advanced stages of the standardization process and are implemented by all major browsers and by **Node**.`

这里的 Node 可能直接翻译为 Node 或者 Node 环境而不是节点更好些？

**Comment by ten-ltw** [comment]
哦是的，感谢。

你可以直接提 PR，很多都没有校对机翻。
